// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication5.DbOperations;

namespace WebApplication5.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("WebApplication5.Il", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<string>("Bolge")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateNull")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("No")
                        .HasColumnType("integer");

                    b.Property<int?>("Numara")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Ils");
                });

            modelBuilder.Entity("WebApplication5.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Birim")
                        .HasColumnType("integer");

                    b.Property<int>("Customer_ID")
                        .HasColumnType("integer");

                    b.Property<int>("ParentUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("User_ID")
                        .HasColumnType("integer")
                        .HasColumnName("Userid");

                    b.Property<int>("User_Name")
                        .HasColumnType("integer")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.HasIndex("User_ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("WebApplication5.Il", b =>
                {
                    b.HasOne("WebApplication5.User", null)
                        .WithMany("Ils")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("WebApplication5.User", b =>
                {
                    b.HasOne("WebApplication5.User", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("User_ID");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("WebApplication5.User", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Ils");
                });
#pragma warning restore 612, 618
        }
    }
}
